### ISSUE TITLE
Amlogic s905x

### ISSUE THREAD

**Issue by predators46** [chencaidy/openwrt-target-amlogic#1]
can you add amlogic s905x?

**Comment by chencaidy** [comment]
Hello Predators,

S905X seems like S905D, but without giga ethernet mac, Phicomm N1 config may help you.

**Comment by predators46** [comment]
> Halo Predator,
> 
> S905X tampak seperti S905D, tetapi tanpa giga ethernet mac, konfigurasi Phcomm N1 dapat membantu Anda.



> Hello Predators,
> 
> S905X seems like S905D, but without giga ethernet mac, Phicomm N1 config may help you.

I don't understand what I should do. I use the file on ophub

https://github.com/ophub/amlogic-s9xxx-openwrt/releases/download/openwrt_s9xxx_lede_2021.11.08.0354/openwrt_s905x_k5.4.158_2021.11.08.0345.img.gz

**Comment by predators46** [comment]
can you give me directions what file i need to edit so amlogic s905x can be used

**Comment by predators46** [comment]
Hy @chencaidy 

is it correct to add for amlogic s905x [patch](https://github.com/predators46/amlogic/compare/s905x?expand=1)
